### ISSUE TITLE
BTC monitoring crashes

### ISSUE THREAD

**Issue by kvetak** [nesfit/kryptoalarm#13]
Behem dvou az tri hodin provozu dojde v urcitem okamziku k tomu, ze prestane BTC monitor reportovat jakekoli adresy. Podle logu dojde k chybe pri pripojeni k RPC serveru, ze ktere se neni schopen zotavit. Je nutne, aby pri vyskytu takoveto chyby se monitoring restartoval.

**Comment by kvetak** [comment]
```
Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
     six.raise_from(e, None)
   File "<string>", line 2, in raise_from
   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
     httplib_response = conn.getresponse()
   File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
     response.begin()
   File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
     version, status, reason = self._read_status()
   File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
   File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
     return self._sock.recv_into(b)
 socket.timeout: timed out
.
 During handling of the above exception, another exception occurred:
.
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
     timeout=timeout
   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 649, in urlopen
     _stacktrace=sys.exc_info()[2])
   File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
     raise six.reraise(type(error), error, _stacktrace)
   File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
     raise value
   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
     chunked=chunked)
   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 388, in _make_request
     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 308, in _raise_timeout
     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
 urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='147.229.9.86', port=8332): Read timed out. (read timeout=20)
.
 During handling of the above exception, another exception occurred:
.
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
     self.run()
   File "/usr/local/lib/python3.6/threading.py", line 864, in run
     self._target(*self._args, **self._kwargs)
   File "./cryptoalarm.py", line 86, in worker
     current_number, block_time = self.process_block(coin, current_number)
   File "./cryptoalarm.py", line 64, in process_block
     tx = coin.get_transaction_io(tx_hash)
   File "/Coin.py", line 82, in get_transaction_io
     vin = reduce(lambda acc, item: self.process_inputs(item) + acc, tx['vin'], [])
   File "/Coin.py", line 82, in <lambda>
     vin = reduce(lambda acc, item: self.process_inputs(item) + acc, tx['vin'], [])
   File "/Coin.py", line 90, in process_inputs
     tx = self.get_transaction(txid)
   File "/Coin.py", line 77, in get_transaction
     return self.rpc('getrawtransaction', hash, 1)
   File "/Coin.py", line 47, in rpc
     response = requests.post(self.url, json=payload, headers=headers, timeout=(cfg.TIMEOUT['connect'], cfg.TIMEOUT['read']))
   File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 112, in post
     return request('post', url, data=data, json=json, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
     return session.request(method=method, url=url, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 513, in request
     resp = self.send(prep, **send_kwargs)
   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 623, in send
     r = adapter.send(request, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
     raise ReadTimeout(e, request=request)
 requests.exceptions.ReadTimeout: HTTPConnectionPool(host='147.229.9.86', port=8332): Read timed out. (read timeout=20)
```

**Comment by kvetak** [comment]
C[36mcryptoalarm    |ESC[0m Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _m
ake_request
     six.raise_from(e, None)
   File "<string>", line 2, in raise_from
   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _m
ake_request
     httplib_response = conn.getresponse()
   File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
     response.begin()
   File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
     version, status, reason = self._read_status()
   File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
   File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
     return self._sock.recv_into(b)
 socket.timeout: timed out

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
     timeout=timeout
   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 649, in urlopen
     _stacktrace=sys.exc_info()[2])
   File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
     raise six.reraise(type(error), error, _stacktrace)
   File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
     raise value
   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
     chunked=chunked)
   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 388, in _make_request
     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 308, in _raise_timeout
     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
 urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='147.229.9.86', port=8332): Read timed out. (read timeout=20)

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
     self.run()
   File "/usr/local/lib/python3.6/threading.py", line 864, in run
     self._target(*self._args, **self._kwargs)
   File "./cryptoalarm.py", line 89, in worker
     current_number, block_time = self.process_block(coin, current_number)
   File "./cryptoalarm.py", line 67, in process_block
     tx = coin.get_transaction_io(tx_hash)
   File "/Coin.py", line 80, in get_transaction_io
     tx = self.get_transaction(hash)
   File "/Coin.py", line 77, in get_transaction
     return self.rpc('getrawtransaction', hash, 1)
   File "/Coin.py", line 47, in rpc
     response = requests.post(self.url, json=payload, headers=headers, timeout=(cfg.TIMEOUT['connect'], cfg.TIMEOUT['read']))
   File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 112, in post
     return request('post', url, data=data, json=json, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
     return session.request(method=method, url=url, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 513, in request
t
     resp = self.send(prep, **send_kwargs)
   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 623, in send
     r = adapter.send(request, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
     raise ReadTimeout(e, request=request)
 requests.exceptions.ReadTimeout: HTTPConnectionPool(host='147.229.9.86', port=8332): Read timed out. (read timeout=20)

**Comment by kvetak** [comment]
Zvetsit dobu timeoutu?

**Comment by vokracko** [comment]
Zajímavé že tahle výjimka vůbec probublá až ven:

```
try:
    response = requests.post(self.url, json=payload, headers=headers, timeout=(cfg.TIMEOUT['connect'], cfg.TIMEOUT['read']))
    ...
except requests.exceptions.RequestException:
    ...
```
```requests.exceptions.ReadTimeout > requests.exceptions.Timeout > requests.exceptions.RequestException```

**Comment by kvetak** [comment]
Spatny merge zdrojovych kodu, aktualne tedy testovani s novymi kody. Doposud vse jede (cca jeden den a kousek).
